import '../app/scss/main.scss';
import Navbar from "./Components/Navbar/Navbar";
import Footer from "./Components/Footer/Footer";
import NProgressProvider from "./Components/NProgress/NProgressProvider";

export const metadata = {
    title: "Oasis Grace",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                {/* <NProgressProvider> */}
                    <Navbar />
                    {children}
                    <Footer />
                {/* </NProgressProvider> */}
            </body>
        </html>
    );
}
